### PR TITLE
mock configuration file

### PR DESCRIPTION
**Pull request by PukieDiederik**
This adds a mock configuration file with a lot of information about each element. The goal of this configuration file is to understand how our configuration file works. It will also assist us in creating our configuration file parser.

This should resolve the following issue:
- [ ] #4

### CODE REVIEW

**Review by gde-alme — APPROVED** [review]

**Comment by PukieDiederik** [comment]
I added mime-types to the configuration file.

**Review by gde-alme — DISMISSED** [review]

**Comment by edgareu1** [comment]
I believe that with this configuration file we have most of the points on the III.3 section of the subject checked. Except for the following ones:
1. Set a default file to answer if the request is a directory;
2. Make the route able to accept uploaded files and configure where they should be saved (...).

For the first point I believe they meant for us to use the `index` directive, eg: `index ["index.html"]`

For the second point I dont think we can check all the subpoints with just this config file. But we could create an upload route as an initial setup, eg:
```
route "/upload" {
    methods ["POST"]
    upload "uploads"
}

```
They also only mention us _making it work_ with `GET` and `POST` methods, but we also added `PATCH` and `PUT`. I am just saying this as an heads up, as that may imply aditional configuration not required by the subject.

**Comment by PukieDiederik** [comment]
> 1. Set a default file to answer if the request is a directory;

I solved this using an error page if the file is a directory (in case directory listing is not enabled). But we can also fix this using an "index" directive.

> 2\. Make the route able to accept uploaded files and configure where they should be saved (...).

This should is not the problem of the webserver. This should be handled by CGI. This does mean that in our example website we will need to give it a way to handle and save files. This is why I did not include it in the configuration file.

**Comment by PukieDiederik** [comment]
I replaced the error page with an "index" directive as was recommended.

And I renamed the enable_directory_listing to auto_index. I did this because its smaller and nginx has a directive by the same name which enables directory listing.

**Comment by edgareu1** [comment]
I believe the "index" directive is good.

But only later, on the testing phase, can I give 100% feedback that it is working as intended by the subject.

Btw, I am not taged as a reviewer, only @gde-alme is.

**Review by gde-alme — APPROVED** [review]
seems fine

**Comment by edgareu1** [comment]
@PukieDiederik you mentioned wanting to do the merges yourself, right?

**Pull request merged**
