### PR TITLE
Request Factory

### PR DESCRIPTION
**Pull request by PukieDiederik**
This PR creates a Request factory which will take input (using the `in` function) and parse to eventually create a request. The benefit this has is that it can take multiple partial requests and generate a full request from it. This will also allow us to implement transfer encoding. There is no error checking on bad requests and an issue will be created for that on acceptance of this PR.

This should solve the following issue:
- #21

### CODE REVIEW

**Comment by PukieDiederik** [comment]
I seemed to have an issue with `response_error` giving me a bad_alloc error. This could be because I messed something up when merging. Would be great if someone can check this.

**Comment by edgareu1** [comment]
Where are you getting that error with the `response_error` function @PukieDiederik ?

I can't seem to be able to replicate it (it is working properly on my side).

**Comment by gde-alme** [comment]
> I seemed to have an issue with `response_error` giving me a bad_alloc error. This could be because I messed something up when merging. Would be great if someone can check this.

Most likely its due to the usage of the function get_path in response_error.
Working on it now

**Review by edgareu1 — APPROVED** [review]
Approved!

**Pull request merged**
