### PR TITLE
gde-alme: parser

### PR DESCRIPTION
**Pull request by gde-alme**
Missing cgi parser.
I don't still fully understand how to parse the cgi and since efreire did a PR asking about it too, waiting for the response.
Still needs some testing with full webserv so to determine if I missed anything else.

### CODE REVIEW

**Review by PukieDiederik — CHANGES_REQUESTED** [review]
It seems you have pushed this branch to the main branch as well. This is not needed (and not suggested). You can create a pull request from you fork to the main branch.
After implementing changes I recommend creating a new PR from the branch on your fork.

I have encountered the following issues when testing your parser:
- `error_pages` should accept a number as the first argument, not a string
- A redirect does not need a root, it does not need to serve any files so it does not need to know where those would be located. In your case it requires the root to be present.
- `auto_index` and `index` are mutually exclusive. Meaning if one exists in a route, the other is not valid
- Adding a comma `,` in an array at the end does not produce an error. Except if you put characters behind it (like spaces)
- Arrays do not allow whitespace (not even spaces) before and after commas
- A server must always have at least one route
- Parsing CGI does not work
- Copy constructor and copy-assignment operator are not implemented.


Things I would like to see:
- A print function on the ServerConfig to more easily debug it.
- `error_pages` accept single arguments (like: `error_pages "s1" "s2")

About your code:
- **Only include headers that you need in that particular file** (and if imported by another header it's still good practice to import it). For example: in `ServerConfig.hpp` has `iostream`, `fstream`, `sstream`, `cstdlib`, `sys/types.h` `dirent.h` imported when they are only needed in the C source file. So you should include them in the `ServerConfig.cpp` file.
- Helper functions (like `isKeyword`, `getParams`, etc...) should not be part of an object and can just be defined in the file.
- If you have somewhat big objects you should pass them by reference (Usually people take 8 bytes as hard limit since this is the size of a pointer). std::string is a "big object". If you do not wish for the string to be modified (which I think you usually don't want when giving it a line) you should mark it as a const reference.
- Name your functions appropriately. `isKeyword` sounds like it will return a boolean. but in your case it seems to return a integer representing a block type. In this case I would rename the function to `identifyKeyword`. And I would also make it return an `enum` OR use `#define` to define each possible output state (like `#define PARSE_TYPE_SERVER 1` for example).
- Your functions should only perform 1 (**AND ONLY ONE**) action described by the name of the function. in `isKeyword` after identifying the keyword you also get the next line and seem to check for brackets for example. This means it does more functions than you expect the function to perform.
- Your object should not have any variables related to the parsing. These should all be defined in the parsing function and be passed to functions that require access to them/need to modify them (in case you only need to access it would be good to have a `const reference`)
- Document what your functions do inside the function. For example in your `isKeyword` function it is hard to figure out what the last block of if/else if's do. You could for example add a comment above it which reads: `compares new line to previous line, checks for opening bracket & checks for comment` (As you can see I have little idea what those lines actually do). You don't need to overdo it (for example I know that getline gets the next line). Adding comments helps should help you to look through code faster and explain what the code does if it's not clear. (The explanations above your functions are really good though. Good job!)
- I recommend exiting functions early if you encounter an error. It would make you use less indentation which makes cleaner code and makes it easier to follow. For example: in `ServerConfig::ServerConfig(const std::string& filepath)` you first open a file, then you have an if statement which checks if the file is open and at the end you have an else statement. By inverting the checking if a file is open (`if (!_fd_conf.is_open())`) you can exit early and you would not need to indent anything that is in the if statement right now.
- You have implemented `atoi`. There are cpp ways to convert strings to numbers, you should look into them. (You have already done the opposite way, it's very similar)
- Instead of using `[namespace]::[attribute]` (`ParserUtils::atoi`) you can also use `namespace ParsingUtils { atoi() }`. This removes confusion about it being an object.
- `ServerConfigServerParser.cpp:257` Take your own advice. Don't be afraid to split functions into multiple smaller functions. (But DO NOT make them part of `ServerConfig` object.)

Even though a lot of changes need to be made. Don't get discouraged. You already did a lot of work and most of the requested changes are just refactoring. The parser worked way better than I expected for a first pass. I am also happy that you took some initiative for improving the config file! Good job and keep on coding!

**Comment by gde-alme** [comment]
I think I've covered all the requested changes. Also tried to push from my fork but ended up messing everything!
Please review the changes and get back at me

**Review by PukieDiederik — CHANGES_REQUESTED** [review]
Issues I encountered:
1. There does not seem to be error checking on the `host` directive. It does not check if it's a valid ipv4 address. It also crashes if I remove a period in the ipv4 address: `host 127.0.0367`

Changes I would like to see:
Check the comments under this review.

Notes:
Good use of the `VERBOSE` definition for debugging. You are almost there, good job!

**Comment by PukieDiederik** [comment]
Merged with master

**Pull request closed without merging**
